### ISSUE TITLE
Negative histogram readings cause bad arith error

### ISSUE THREAD

**Issue by russelldb** [boundary/bear#7]
https://github.com/boundary/bear/blob/master/src/bear.erl#L316 seems to be the culprit.

I'm posting this issue for discussion. It is reasonable to argue that there should _never_ be a negative reading. In which case…should I 
- add a PR to folsom that drops negative readings silently?
- Or `bad arg` negative histogram readings (leaving it up to the user to detect and drop / correct / handle appropriately) negative readings?

For me, folsom histogram `bad arg`ing negative readings is the most logical, but somewhat interface breaking.

I'm just after your thoughts / input on the best location to solve this problem.

**Comment by joewilliams** [comment]
I think I would rather bubble up the bad arg and force the user to deal with them rather than drop them silently.

**Comment by joewilliams** [comment]
@russelldb should this fix this issue? https://github.com/boundary/bear/pull/14

**Comment by joewilliams** [comment]
This should be fixed in bear HEAD due to https://github.com/boundary/bear/pull/14 I hope to be cutting bear and folsom tags that include this fix soon.
